---
title: "Конкурентни предимства, пазарна структура и стратегическо позициониране"
author: "Виктор Аврамов"
format: revealjs
---

# Видове разходи на фирмата (продължение), ценова еластичност

## Ценова еластичност (продължение)

Функцията на търсенето има наклон, който е интересен, защото:

::: {.incremental}
- Показва как търсенето се променя с промяната на цената
- И тази промяна може да се изчислява като игнорираме мерните единици
:::
## Ценова еластичност (продължение)

Промяната на търсенето $q$ вследствие на цената $p$ може да се изчисли като $\Delta q / \Delta p$, но тогава стойността зависи от мерните единици.

Затова дефинираме ценовата еластичност по следния начин:
$$ \epsilon \equiv -\frac{dq}{dp} \frac{p}{q} \approx \frac{\Delta q/q}{\Delta p/p} $$
## Ценова еластичност (продължение)

Първата част $-\frac{dq}{dp} \frac{p}{q}$ е точната дефиниция: първата производна на фукнцията на търсенето спрямо цената, което за малки изменения на $p$ е приблизително равно на процентното изменение на количеството спрямо процетното изменение на цената $\frac{\Delta q/q}{\Delta q/q}$. 

## Разходи на фирмата
Както споменахме, разходите на формата могат да се дефинират като:

::: {.incremental}
- Фиксирани: тези, които не зависят от обема на производството
- Вариращи: тези, които зависят и при нулево производство ще бъдат равни на нула
- Общи: сумата на фиксираните и вариращите
- Средни: общите, разделени на нивото на производство
- Пределни: разходите за следващата единица продукция
:::

## Разходи на фирмата (продължение)

Вече е казвано, че пределните разходи са централни за икономическите решения. 
Лесен начин да мислим за тях е като за разликата между общите разходи за производството на $q+1$ и $q$ единици продукция.
Казано точно, това са "инкрементални" разходи, а пределените разходи са първата производна на фукцията на пълните разходи. 

## Разходи на фирмата (продължение)

Ако означим функцията на пълните разходи като $TC(q)$, функцията на пределните означаваме е  $MC(q) = TC'(q)$

Какви видове разходи са следните:

::: {.incremental}
- Наемът на една шевна машина
- Дневната заплата на оператора на машината
:::

## Разходи на фирмата (продължение)

Това, което е важно да се подчертае е, че пределните разходи са релевантни когато се решава колко да се произвежда, а средните разходи са релевантни когато се решава дали да се произвежда изобщо.

## Още от същото: алтернативни разходи и потънали разходи

Алтернативните разходи се дефинират като пропуснатите ползи от неизползването на дадените ресурси за следващата най-добра алтернатива. 

Потъналите разходи са просто разходи, които нямат алтернативно използване. 

## Още от същото (продължение)

Например, нека ТЕЦ е изградена на много висока цена и при изграждането й е изчислено, че цената на енергията от нея, нужна за въстановяване на фиксираните и варищите разходи е 100 лв./MWh. Само вариращите разходи възлизат на 50 лв./MWh.

Ако след изграждането й се разкрива възможност за нова мощност, която има само вариращи разходи от 70 лв./MWh. Трябва ли старата мощност да се изостави за сметка на новата?

## Изводи

Бизнес решенията трябва да се базират на концепцията за икономически разходи. Икономическите разходи се разлиават от реалните по това, че включват алтернативните и изклюват потъналите разходи. 


## to do:  Ценова еластичност: работа с пазарни данни

