---
title: "Модели на конкуренцията: Пазарен монопол и регулация"
author: "Виктор Аврамов"
format: revealjs
---

## Пазарен монопол: първа дефиниция

Чист **пазарен монопол** има на този пазар, при който една фирма/продавач/производител има 100% пазарен дял.

::: incremental
- Трудно можем да намерим примери за това..

- освен при предоставянето на публични услуги като вода, улично осветление и др.
:::

## Пазарен монопол

На практика, основно се интересуваме от пазари, на които съществува **доминираща** фирма: такава, която притежава пазарен дял между 50 и 100% и няма близък съперник, т.е. няма друга фирма, която има значителен пазарен дял (с това са свързани следващи теми)

## Пазарен монопол - продължение

::: incremental
Нашият модел се базира на допускането, че имаме добре дефиниран пазар (как дефинираме пазарите?) с един доставчик.

Използваме файловете симулация и симулация 1 в Moodle.
:::


## Пазарен монопол - продължение

::: incremental
- Може да се допусне, че монополистът избира цена $p$, а потребителите имат функция на търсене $D(p)$ 
- Можем да направим и **обратното** представяне: за да продаде количество $q$, монополистът определя цена $P(q)$, където $P(\cdot)$ е инверсната функция на $Q(\cdot)$. 
- Произвеждайки $q$, монополистът има разходи $C(q)$. 
- Монополистът избира цената, която максимизира печалбата му.
:::

## Пазарен монопол - продължение

Монополистът максимизира печалбата си когато пределните приходи са равни на пределната цена (може ли интуитивно да се демонстрира това?). Може да се докаже, че това равенство води до следното:

$$ \frac {p - MC}{p} = \frac {1}{\epsilon} $$
където $\epsilon = -\frac{dq}{dp} \frac{p}{q}$ е еластичността на търсенето.

## Пазарен монопол - продължение

Можем да използваме алтернативната формула на горното равенство:

$$p  \left(1 - \frac {1}{\epsilon}\right) = MC$$

## Пазарен монопол - продължение

Двете форми на горното равенство ни казват, че:

::: incremental
- С намаляването на еластичността на търсенето, нараства разликата между цената и пределните разходи за монополиста.
- Печалбата на монополиста зависи от еластичността на търсенето.
- Монополист, който е изправен пред мноог силно еластично търсене, има печалба на нивото на съвършената конкуренция.
:::

## Пазарен монопол - пример

::: incremental
- Нека пределните разходи на една фирма за 1 бр. продукт са 40 лв. (и са константни) и пазарната цена е 100 лв.за продукт. 
- Ако фирмата е изчислила, че пазарното търсене е 2.0 (и е константно), трябва ли да намали, да запази или увеличи пазарна цена?
- Имаме: $\frac{p - MC}{p}=\frac{1}{\epsilon}$ или $\frac{100 - 40}{100}=0,6$ което е по-малко от $1/2= 0,5$
- Виждаме, че оптималната цена би била по-ниска; каква?
:::

## Пазарен монопол и пазарна сила

В началото казваме, че примерите за пазарни монополисти са ограничени днес. Много от публичните услуги, на които може да има монополисти са либерализирани. Това води до два практически въпроса:

::: incremental
- Защо да анализираме пазарни монополи, ако липсват на практика?
- Как да ги дефинираме, ако всъщност са важни за нас.
:::

## Пазарен монопол и пазарна сила - примери

::: incremental
- [Apple](https://ec.europa.eu/commission/presscorner/detail/en/IP_22_2764)
- [Gazprom](https://ec.europa.eu/commission/presscorner/detail/en/MEMO_15_4829)
- [Google](https://ec.europa.eu/commission/presscorner/detail/en/MEMO_17_1785)
- [Microsoft](https://ec.europa.eu/commission/presscorner/detail/en/IP_13_196)
:::

## Пазарен монопол и пазарна сила - примери

Дискусия: [Apple](https://www.ft.com/content/75891d95-4432-4571-83df-b4cdf82d5da5) имат 50% дял на пазара на смартфони в САЩ, но под 20% на [пазара](https://gs.statcounter.com/os-market-share/desktop/worldwide) на персонални компютри.

Ако искаме да дефинираме пазарните монополи на базата на пазарния дял, може да имаме проблеми с дефинирането на пазара. Различни дефиниции ще доведат до различни пазарни дялове.

## Пазарен монопол и пазарна сила - втора дефиниция

**Размерът на пазарната сила** на един монополист е в инверсна/обратна/обратнопропорционална зависимост от еластичността на търсенето на съответния пазар.

## Регулация

Ако фиксираните разходи за едно производство са много високи/ако съществуват съществени икономии от мащаба, пазарът може да не бъде конкурентен. 

Пример за това са естествените монополи.


## Регулация

Нека разходите на фирмата са дефинирани като $C = F + cq$, където $F$ са фиксираните разходи, а $c$ са пределните разходи. 
В отсъствието на регулация, монополистът избира  монополна цена $p^m$, която, както видяхме е по-висока от пределните разходи. 
Вариращата печалба е $\pi = q^m(p^m-c)$, нетната печалба е $\pi - F$. 

## Регулация

Просто решение би било регулаторът да определни пазарна цена, на която монополистът да продава, която да е равна на пределните разходи: $p^r=c$. 
Тогава количеството на пазара ще бъде по-високо от монополното: $q^m < q^r$, което ще доведе до ефикасно разпределение на ресурсите.
Но може да доведе до загуба за монополиста, защото $\pi = 0$ и нетната печалба е $- F$.

## Регулация

За да се реши това, регулаторът може да определи субсидия за фирмата, равна на $F$. 

Това може да доведе до други проблеми:

::: incremental
- първо, за изплащаневто на $F$, регулаторът може да вдигне общото ниво на разходи на потребителите, например чрез данъци;
- второ, може монополистът да въздейства на регулатора за да повиши нивото на субсидията $F$ до това ниво, което е равно на монополната печалба.
:::

## Регулация

Вместо това, регулаторът може да прибегне до определяне на регулирана цена, равна на *средните* разходи: $p^a=AC(q^a)$ и $q^a=D(p)$. 

Това е известно в практиката като регулация, базирана на норма на възвръщаемост.

Може ли това решение също да доведе до проблеми?

## Регулация

Регулаторната цена, базирана на норма на възвръщаемост не предоставя на фирмата стимули за минимизиране на разходите.

В термините на теорията на регулацията, това е стимулиращ механизъм с ниска сила/нисък интензитет.

::: incremental
- Може ли да имаме стимулиращ механизъм с висока сила/висок интензитет?

- Да: можем да определим таван на цените.
:::

## Регулация

Ако определим таван на цените, може ли фирмата да инвестира огромни средства за редукция на разходите си, които след това да си възвърне чрез регулираната цена?

Да, но само ако регулаторът не може да наблюдава поведението й.

На практика регулаторът определя цените на определени кратки периоди, които правят такива редуцкия/спестявания трудни.

Освен това, фирмата не е стимулирана да повишава качеството. 
