---
title: "Стратегическо взаимодействие: игри, стратегии, равновесие"
author: "Виктор Аврамов"
format: revealjs
---

## Дефиниция

**Игра** наричаме стилизиран модел, който репрезентира стратегическото поведение на група от *играчи*, които имат свои *стратегии*, където *резултатът* за всеки играч зависи от неговата стратегия и от стратегиите на останалите играчи.

## Затворническа дилема (вариация)

|         |       |         |
|---------|-------|---------|
|         | Мълчи | Предава |
| Мълчи   | 5, 5  | 3, 6    |
| Предава | 6, 3  | 4, 4    |

Това е пример за игра в *нормална форма*

## Още дефиниции

*Доминираща* стратегия е тази, чиито резултати са равни или по-добри при всяка комбинация от стратегии на останалите играчи

*Доминирана* стратегия е тази, чиито резултати са равни или по-добри при всяка комбинация от стратегии на останалите играчи

## Последователно елиминиране на доминирани стратегии

|     |      |      |      |
|-----|------|------|------|
|     | L    | C    | R    |
| T   | 1, 1 | 2, 0 | 1, 1 |
| M   | 0, 0 | 0, 1 | 0, 0 |
| B   | 2, 1 | 1, 0 | 2, 2 |

## Допускане за колективна рационалност

|     |         |      |
|-----|---------|------|
|     | L       | C    |
| T   | 1, 0    | 1, 1 |
| M   | -100, 0 | 2, 1 |

::: incremental
- Не е достатъчно играчите да са рационални

- Трябва играчите да знаят, че останалите играчи са рационални
:::

## Ако нямаме доминиращи стратегии?

|     |      |      |      |
|-----|------|------|------|
|     | L    | C    | R    |
| T   | 2, 1 | 2, 2 | 0, 1 |
| M   | 1, 1 | 1, 1 | 1, 1 |
| B   | 0, 1 | 0, 0 | 2, 2 |

::: incremental
- Игрите могат да имат решения и ако играчите праят допускания какво биха предприели рационалните им опоненти
:::

## Равновесие на Неш

::: {.box}
Група стратегии са равновесие на Неш ако няма играч, който може едностранно да спечели повече, ако промени стратегията си.
:::

## Игри в разширена форма

Навлизане на нов пазар

```{mermaid}
graph TD

    A((1)) -->|навлиза| B[П1 = 0 <br> П2 = 50]
    A((1)) -->|не навлиза| C((2))
    C -->|възпира| D[П1 = -10 <br> П2 = -10]
    C -->|не възпира| E[П1 = -10 <br> П2 = 20]
```


## Обратна индукция

В предишната репрезентация имаме две равновесия на Неш: (навлиза, не възпира) и (не навлиза, възпира). Защо?

::: incremental
- Можем ли да елиминираме контраинтуитивни равновесия?
:::


## Обратна индукция

Можем да елиминираме контраинтуитивни, или неразумни равновесия с помощта на обратна индукция:

::: incremental
- първо, на втория ход допускаме, че разумното решение за Играч 2 е (не възпира);
- второ, след като знаем, че на втория ход разумното решение за Играч 2 е (не възпира), на първия ход оптималното решение за Уграч 1 е (навлиза).
:::

## Под-игри и под-игрово равновесие

::: incremental
- Без да даваме формална дефиниция, наричаме *под-игра* всяка обособена част от една игра, която може да се третира като самостоятелна игра в рамките на цялата.

- Използвайки обратна индукция, може да решим първоначално всяка суб-игра в рамките на играта и да използваме тези решения за решение на цялата игра.

- Полученото равновесие наричаме суб-игрово перфектно равновесие.
:::

## Достоверни ангажименти

Нека играч 2 е задължен от договор да избере (възпира) ако играч 1 избере (навлиза). Договорът казва, че ако Играч 2 не избере (възпира), а (̂не възпира), му се налага глоба от -40.

Можем да модифицираме играта, като добавим този вариант и в началото й допуснем решението на Играч 2 дали да приеме или не такъв договор.

## Достоверни ангажименти

```{mermaid}
graph TD
    A((2)) --> |договор| B((1))
    A((2)) --> |без договор|C((1))
    C((1)) -->|не навлиза| D[П1 = 0 <br> П2 = 50]
    C((1)) -->|навлиза| E((2))
    E -->|възпира| F[П1 = -10 <br> П2 = -10]
    E -->|не възпира| G[П1 = -10 <br> П2 = 20]
    B --> |не навлиза| I[П1 = 0 <br> П2 = 50]
    B((1)) -->|навлиза| J((2))
    J -->|възпира| K[П1 = -10 <br> П2 = -10]
    J -->|не възпира| L[П1 = -10 <br> П2 = -20]
```


## Достоверни ангажименти

Сега играта е променена. Как?

## Достоверни ангажименти


Ако достоверните ангажименти са възможни:

::: incremental
- Те могат да имат значителна стратегическа роля
- Трябва да моделираме това, като променим резултатите на играчите, които се ангажират
- На практика, ангажиментите създават нова игра!
:::

## Достоверни ангажименти, краткосрочни и дългосрочни решения

В практиката можем да приемем, че фирмите взимат дългосрочни и краткосрочни решения.

::: incremental
- Посочете примери!
- Дългосрочните решения се взимат първо, а краткорочните са подчинени на тях
:::

## Достоверни ангажименти, краткосрочни и дългосрочни решения

На пазарите фирмите избират производствен капацитет и пазарна цена. Ако искаме да моделираме това в проста игра, кое решение ще бъде първо и кое - второ?



